### ISSUE TITLE
Error running ReproBot without Docker

### ISSUE THREAD

**Issue by Connor-fire** [USC-SQL/ReproBot-Artifact#1]
Sorry to bother you，
I tried running ReproBot without Docker based on readme. But it doesn't work, it seems to be Error in ./utils/GraphieTest-1.0-SNAPSHOT-jar-with-dependencies.jar. The screenshot is shown below.

![pic](https://github.com/USC-SQL/ReproBot-Artifact/assets/55130798/49f98bad-c14e-4f54-8b9e-1b7e8ef94fe0)

Looking forward to your reply.

**Comment by Vermouth-hub** [comment]
I have the same problem. Do you solve it now?
